//! Unit tests for correlation ID uniqueness (F-13).
//!
//! Verifies that the ACP handshake and runtime driver generate IDs that:
//!
//! - Match the `intercom-{purpose}-{uuid}` pattern (S022, S023)
//! - Are unique across 10,000 sequential calls (S024)
//! - Are unique across concurrent sessions (S026)
//!
//! These tests FAIL before the F-13 implementation because the current code
//! uses static constants (`intercom-init-1`, `intercom-sess-1`,
//! `intercom-prompt-1`) and a global `AtomicU64` counter, which produce
//! collisions across sessions and restarts.

use agent_intercom::acp::handshake::generate_correlation_id;
use uuid::Uuid;

// ── T023 / S022 — handshake IDs match intercom-{purpose}-{uuid} pattern ──────

/// Handshake `initialize` ID must match `intercom-init-{uuid}` (S022).
#[test]
fn init_id_matches_intercom_init_uuid_pattern() {
    let id = generate_correlation_id("init");
    assert!(
        id.starts_with("intercom-init-"),
        "S022: init ID must start with 'intercom-init-', got: {id}"
    );
    let uuid_part = id
        .strip_prefix("intercom-init-")
        .expect("prefix confirmed above");
    Uuid::parse_str(uuid_part).unwrap_or_else(|e| {
        panic!("S022: suffix of init ID must be a valid UUIDv4, got '{uuid_part}': {e}")
    });
}

/// Handshake `session/new` ID must match `intercom-sess-{uuid}` (S022).
#[test]
fn session_new_id_matches_intercom_sess_uuid_pattern() {
    let id = generate_correlation_id("sess");
    assert!(
        id.starts_with("intercom-sess-"),
        "S022: session/new ID must start with 'intercom-sess-', got: {id}"
    );
    let uuid_part = id
        .strip_prefix("intercom-sess-")
        .expect("prefix confirmed above");
    Uuid::parse_str(uuid_part).unwrap_or_else(|e| {
        panic!("S022: suffix of session/new ID must be a valid UUIDv4, got '{uuid_part}': {e}")
    });
}

/// Handshake `session/prompt` ID must match `intercom-prompt-{uuid}` (S022).
#[test]
fn prompt_id_matches_intercom_prompt_uuid_pattern() {
    let id = generate_correlation_id("prompt");
    assert!(
        id.starts_with("intercom-prompt-"),
        "S022: prompt ID must start with 'intercom-prompt-', got: {id}"
    );
    let uuid_part = id
        .strip_prefix("intercom-prompt-")
        .expect("prefix confirmed above");
    Uuid::parse_str(uuid_part).unwrap_or_else(|e| {
        panic!("S022: suffix of prompt ID must be a valid UUIDv4, got '{uuid_part}': {e}")
    });
}

// ── T024 / S023 — runtime prompt IDs match UUID pattern ──────────────────────

/// Runtime prompt IDs generated by the driver must also conform to the
/// `intercom-{purpose}-{uuid}` pattern (S023).
///
/// The driver uses a different code path than the handshake but must produce
/// IDs of the same form.
#[test]
fn runtime_prompt_ids_match_uuid_pattern() {
    // The driver generates "intercom-prompt-{uuid}" for session/prompt messages.
    let id = generate_correlation_id("prompt");
    assert!(
        id.starts_with("intercom-prompt-"),
        "S023: runtime prompt ID must start with 'intercom-prompt-', got: {id}"
    );
    let uuid_part = id
        .strip_prefix("intercom-prompt-")
        .expect("prefix confirmed above");
    Uuid::parse_str(uuid_part)
        .unwrap_or_else(|e| panic!("S023: runtime prompt ID UUID part is invalid: {e}"));
}

/// Each call to `generate_correlation_id` must produce a fresh value
/// (no static or cached ID is returned).
#[test]
fn two_calls_produce_different_ids() {
    let a = generate_correlation_id("check");
    let b = generate_correlation_id("check");
    assert_ne!(
        a, b,
        "S023: two consecutive calls must produce different IDs — static IDs are forbidden"
    );
}

// ── T025 / S024 — 10,000 IDs with zero collisions ────────────────────────────

/// Generate 10,000 correlation IDs sequentially and confirm zero collisions.
///
/// With static constants (pre-F-13), all 10,000 IDs are identical and the
/// `HashSet` size is 1. After F-13, each ID is a fresh UUID and the size
/// must be 10,000.
#[test]
fn ten_thousand_ids_have_zero_collisions() {
    let ids: std::collections::HashSet<String> = (0..10_000)
        .map(|_| generate_correlation_id("test"))
        .collect();

    assert_eq!(
        ids.len(),
        10_000,
        "S024: 10,000 generated IDs must all be unique — zero collisions allowed"
    );
}

// ── T026 / S026 — concurrent sessions produce distinct IDs ───────────────────

/// Spawn 20 concurrent async tasks, each generating a correlation ID.
///
/// All 20 IDs must be distinct, confirming that concurrent sessions do not
/// observe the same correlation ID (S026).
#[tokio::test]
async fn concurrent_sessions_produce_distinct_ids() {
    let handles: Vec<_> = (0..20)
        .map(|_| tokio::spawn(async move { generate_correlation_id("session") }))
        .collect();

    let mut ids = std::collections::HashSet::new();
    for handle in handles {
        let id = handle.await.expect("spawned task must complete");
        ids.insert(id);
    }

    assert_eq!(
        ids.len(),
        20,
        "S026: 20 concurrent sessions must produce 20 distinct IDs"
    );
}
